name: base
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - psutil
  - python=3.9.7
  - conda-forge::termcolor
  - conda-forge::tensorboard
  - conda-forge::black
  - conda-forge::hydra-core
  - anaconda::ipython
  - anaconda::path
  - pip
  - openblas-devel
  - tqdm
  - nose
  - cython
  - pysoundfile
  - pip:
    - jsonargparse[signatures]
    - torchvision
    - progressbar2
    - exman~=0.1.9
    - pytorch-lightning==2.0.0
    - numpy~=1.20.1
    - PyYAML~=5.4.1
    - scipy~=1.6.1
    - pandas~=1.2.3
    - tqdm~=4.59.0
    - imageio~=2.9.0
    - matplotlib~=3.3.4
    - seaborn~=0.11.1